--- #YAML:1.0
name:               CDP
version:            0.032
abstract:           Perl wrapper R1Soft CDP (Constant Data Protection) API.
author:
    - jon <jon@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Frontier::Client:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
